changeversion: '3.9'
services:
  db:
    image: mysql:8
    container_name: db
    networks:
      - adr
    restart: always
    env_file:
      - docker.env
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adr-waybill:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: adr-waybill
    ports:
      - "8092:8092"
    restart: on-failure
    networks:
      - adr
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - docker.env
    tty: true
    stdin_open: true

networks:
  adr:
    driver: bridge
    name: adr