version: '3.8'
services:
  mysql-3310:
    image: mysql:8
    container_name: mysql-3310
    networks:
      - adr-waybill
    restart: always
    env_file:
      - .env
    ports:
      - "3310:3306"

  adr-waybill:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: adr-waybill
    ports:
      - "8092:8092"
    restart: on-failure
    networks:
      - adr-waybill
    depends_on:
      - mysql-3310
    env_file:
      - .env
    tty: true
    stdin_open: true

networks:
  adr-waybill:
    driver: bridge
    name: adr-waybill