insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (8540, 'I', 3, 'duis bibendum morbi non', 'I');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (6323, 'I', 6, 'suspendisse ornare consequat lectus in', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (4127, 'I', 5, 'consequat', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (7156, 'I', 9, 'duis', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (3104, 'I', 7, 'et', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (7063, 'III', 1, 'lobortis ligula', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (4460, 'III', 4, 'rutrum at lorem integer', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (8747, 'III', 1, 'pede venenatis non sodales sed tincidunt', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (7592, 'II', 3, 'vel ipsum praesent blandit lacinia', 'I');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (7988, 'III', 5, 'justo lacinia eget tincidunt', 'I');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (9377, 'III', 7, 'vel pede morbi porttitor', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (3820, 'III', 8, 'ornare imperdiet', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (9603, 'I', 3, 'eu massa donec dapibus duis', 'I');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (3117, 'III', 7, 'vestibulum ante ipsum primis', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (3361, 'III', 8, 'tincidunt', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (9117, 'I', 9, 'vel dapibus at diam nam tristique', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (8808, 'I', 7, 'at', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (5756, 'III', 1, 'habitasse platea', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (5950, 'II', 2, 'consectetuer eget rutrum at lorem integer', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (6325, 'III', 2, 'in leo maecenas pulvinar', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (4063, 'III', 9, 'libero quis orci nullam molestie', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (8063, 'I', 1, 'feugiat non pretium', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (8299, 'III', 8, 'primis in faucibus orci luctus', 'I');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (2634, 'I', 9, 'tellus semper', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (3209, 'I', 4, 'lacinia nisi venenatis tristique', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (4239, 'II', 9, 'maecenas tristique est', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (3484, 'I', 8, 'ultrices posuere cubilia curae mauris', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (7807, 'II', 5, 'sed sagittis nam congue risus semper', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (4833, 'I', 2, 'luctus et ultrices', 'I');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (6799, 'II', 1, 'quisque arcu', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (9534, 'II', 3, 'ultricies eu', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (5991, 'II', 8, 'aenean sit amet justo morbi', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (6976, 'III', 2, 'vivamus', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (1040, 'I', 3, 'justo', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (3578, 'III', 3, 'ante', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (5246, 'III', 4, 'ipsum dolor sit', 'III');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (5612, 'III', 6, 'dui nec nisi volutpat eleifend donec', 'II');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (7069, 'III', 3, 'sit amet consectetuer', 'I');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (7661, 'II', 1, 'a feugiat et', 'I');
insert into uns (un_number, un_class, un_labels, un_name_and_description, un_packing_group) values (2240, 'II', 2, 'ut suscipit a feugiat', 'I');